name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the deployment when you push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project
      - name: Build the project
        run: npm run build --configuration production

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/axis-board  # This is the folder containing the build output
